---
title: "progress-report-emaruska"
output: html_document
date: "2024-04-17"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#install.packages("rvest")
library(Lahman)
head(HallOfFame, 3)
```

```{r}
library(rvest)
url <- "https://www.baseball-reference.com/awards/hof_2023.shtml"
html <- read_html(url)
tables <- html_table(html)
data2023 <- tables[[1]]
data2023
```

```{r}
library(tidyverse)
write.csv(data2023, "temp.csv", row.names=FALSE)
data2023 <- read_csv("temp.csv", skip = 1, show_col_types =FALSE)
data2023

data2023$Name <- gsub("X-", "", data2023$Name)

```

```{r}
all_links <- html %>% html_nodes("table:nth-child(1)") %>% html_nodes("a") %>%
  lapply(function(link) {
  href <- html_attr(link, "href")
  text <- html_text(link)
  return(data.frame(href = href, text = text, stringsAsFactors = FALSE))
})

links <- do.call(rbind, all_links)

forPlayerID <- separate(links, href, into = c("blank", "category", "remove", "bbrefID"), sep = "/") %>%
  select(
    category,
    bbrefID,
    Name = text
  )

forPlayerID$bbrefID <- gsub(".shtml", "", forPlayerID$bbrefID)

forPlayerID
```


```{r}
forPlayerID <- inner_join(forPlayerID, Lahman::People, by ="bbrefID") %>% select(
  playerID,
  Name,
  category
)

forPlayerID
```

```{r}
data2023 <- inner_join(forPlayerID, data2023, by="Name") %>% mutate(
  yearID = 2023, 
  votedBy = "BBWAA", 
  ballots = 389, 
  needed = 292,
  inducted = ifelse(Votes>=needed, "Y", "N"),
  category = ifelse(category == 'players', "Player", NA), 
  needed_note = NA
) %>% select(
  playerID,
  yearID,
  votedBy,
  ballots,
  needed,
  votes = Votes,
  inducted,
  category, 
  needed_note
)
```

```{r}
data2023
```


```{r}
hof <- Lahman::HallOfFame
hof
hallOfFameUpdates <- rbind(hof, data2023)
```

```{r}
readr::write_csv(hallOfFameUpdates, file="HallOfFame.csv")
```

