---
title: "progress-report-smashraf321"
author: "Ashraf Shaikh"
date: "4/17/2024"
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit the README.Rmd file -->

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

# Lab report #4

```{r}
library(Lahman)
head(HallOfFame, 3)

```

we need the foll:
yearID: (2023) DONE
votedBy: (BBWAA) DONE
playerID: scrape
ballots: 389 but scrape it DONE
needed: 292 but scrape it DONE
votes: (votes) scrape it
inducted: if votes > needed then y 
category: player?
needed_note: just empty NA

My stuff

```{r}
library(rvest)
url <- "https://www.baseball-reference.com/awards/hof_2023.shtml"
html_content <- read_html(url)
tables <- html_table(html_content)
```

testing tables

```{r}

#tables[[1]]
#tables[[2]]
# we only care about table 1

data_23 <- tables[[1]]
str(data_23)
head(data_23, 1)
name_idx <- which(head(data_23, 1) == "Name")
name_idx # to be used for playerID
votes_idx <- which(head(data_23, 1) == "Votes")
votes_idx # to be used for votes

text_strings <- html_content %>% html_nodes("div") %>% lapply(function(x) {x %>% html_text() %>% trimws()})

# only filter out stuff that has that regex for total ballots
# Regex pattern
pattern <- "^\\d+ total ballots \\(\\d+ votes needed for election\\)$"

matches <- regmatches(text_strings, regexpr(pattern, text_strings))
print(matches)

# Extract numbers as a list
numbers_list <- regmatches(matches[[1]], gregexpr("\\d+", matches[[1]]))

# Print extracted numbers as a list
print(numbers_list)

num_ballots <- as.numeric(numbers_list[[1]][1])

num_needed <- as.numeric(numbers_list[[1]][2])

print(num_ballots)

print(num_needed)


```


```{r}
data_23_clean <- data.frame(playerID = character(28),
                            yearID = integer(28),
                            votedBy = character(28),
                            ballots = numeric(28),
                            needed = numeric(28),
                            votes = numeric(28),
                            inducted = factor(28),
                            category = factor(28),
                            needed_note = character(28))



data_23_clean$playerID <- data_23[2:nrow(data_23), name_idx]
data_23_clean$votes <-  data_23[2:nrow(data_23), votes_idx]

data_23_clean$playerID <- as.character(unlist(data_23_clean$playerID))
data_23_clean$votes <- as.numeric(unlist(data_23_clean$votes))



data_23_clean <- data_23_clean %>% mutate(yearID = as.integer(2023),
                                          votedBy = "BBWAA",
                                          ballots = num_ballots,
                                          needed = num_needed,
                                          category = factor("Player"),
                                          needed_note = NA)

data_23_clean <- data_23_clean %>% mutate(inducted = factor(ifelse(votes>=num_needed, "Y", "N")))


```


```{r}

new_HallOfFame <- rbind(HallOfFame, data_23_clean)

# View the last `n` rows of the data frame
last_n_rows <- new_HallOfFame[(nrow(new_HallOfFame) - 35 + 1):nrow(new_HallOfFame), ]

# Print the last `n` rows
print(last_n_rows)

write.csv(new_HallOfFame, file="updated_HallOfFame.csv", row.names = FALSE)
```


