---
title: "Progress Report"
author: "Ryan Ledbetter"
date: "2024-04-17"
output: html_document
---
```{r}
library(rvest)
library(tidyr)
library(Lahman)
library(tidyverse)
```

```{r}
url <- "https://www.baseball-reference.com/awards/hof_2023.shtml"
html <- read_html(url)
tables <- html_table(html)
data2023 <- tables[[1]]

write.csv(data2023, "temp.csv", row.names=FALSE)
data2023 <- read_csv("temp.csv", skip = 1, show_col_types =FALSE)

allLinks <- html %>% html_nodes("table:nth-child(1)") %>% html_nodes("a") %>%
  lapply(function(link) {
  href <- html_attr(link, "href")
  text <- html_text(link)
  return(data.frame(href = href, text = text, stringsAsFactors = FALSE))
})

links <- do.call(rbind, allLinks)

PlayersInfo <- separate(links, href, into = c("blank", "category", "remove", "bbrefID"), sep = "/") %>%
  select(
    category,
    bbrefID,
    Name = text
  )

PlayersInfo$bbrefID <- gsub(".shtml", "", PlayersInfo$bbrefID)

PlayersInfo <- inner_join(PlayersInfo, Lahman::People, by ="bbrefID") %>% select(
  playerID,
  Name,
  category
)
```
```{r}


data2023 <- inner_join(PlayersInfo, data2023, by="Name") %>% mutate(
  yearID = 2023, 
  votedBy = "BBWAA", 
  ballots = 389, 
  needed = 292,
  inducted = ifelse(Votes>=needed, "Y", "N"),
  category = ifelse(category == 'players', "Player", NA), 
  needed_note = NA 
) %>% select(
  playerID,
  yearID,
  votedBy,
  ballots,
  needed,
  votes = Votes,
  inducted,
  category,
  needed_note
)
```

```{r}
hofUpdated <- rbind(hof, data2023)
readr::write_csv(hofUpdated, file="HallOfFame.csv")
```

